import { createApp } from "vue";
import App from "./App.vue";

import router from "./router";
import store from "./store";

import VueLazyload from "vue3-lazyload";

import "./index.scss";

import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";

import { faYoutube, faUnsplash } from "@fortawesome/free-brands-svg-icons";
library.add(faYoutube, faUnsplash);

import {
  faArrowsRotate as fasArrowsRotate,
  faAt as fasAt,
  faBook as fasBook,
  faBoxesPacking as fasBoxesPacking,
  faChartLine as fasChartLine,
  faCheck as fasCheck,
  faChevronUp as fasChevronUp,
  faChevronDown as fasChevronDown,
  faCircle as fasCircle,
  faCircleQuestion as fasCircleQuestion,
  faClose as fasClose,
  faCog as fasCog,
  faDoorClosed as fasDoorClosed,
  faDoorOpen as fasDoorOpen,
  faDownLong as fasDownLong,
  faFaceLaugh as fasFaceLaugh,
  faFileImage as fasFileImage,
  faGripVertical as fasGripVertical,
  faHashtag as fasHashtag,
  faHeart as fasHeart,
  faHeartPulse as fasHeartPulse,
  faImage as fasImage,
  faImages as fasImages,
  faInfo as fasInfo,
  faLifeRing as fasLifeRing,
  faListCheck as fasListCheck,
  faListOl as fasListOl,
  faMicrophoneLines as fasMicrophoneLines,
  faMoon as fasMoon,
  faPaintRoller as fasPaintRoller,
  faPenToSquare as fasPenToSquare,
  faPersonCircleQuestion as fasPersonCircleQuestion,
  faPhotoFilm as fasPhotoFilm,
  faPlugCircleBolt as fasPlugCircleBolt,
  faPlugCirclePlus as fasPlugCirclePlus,
  faPlus as fasPlus,
  faShield as fasShield,
  faSquare as fasSquare,
  faSun as fasSun,
  faTachographDigital as fasTachographDigital,
  faToolbox as fasToolbox,
  faTriangleExclamation as fasTriangleExclamation,
  faTurnDown as fasTurnDown,
  faTurnUp as fasTurnUp,
  faUpLong as fasUpLong,
  faUser as fasUser,
  faUserCheck as fasUserCheck,
  faUserClock as fasUserClock,
  faUserGroup as fasUserGroup,
  faUserMinus as fasUserMinus,
  faUserPlus as fasUserPlus,
  faUserShield as fasUserShield,
  faWrench as fasWrench,
} from "@fortawesome/pro-solid-svg-icons";

import {
  faArrowsRotate as farArrowsRotate,
  faAt as farAt,
  faBook as farBook,
  faBoxesPacking as farBoxesPacking,
  faChartLine as farChartLine,
  faCheck as farCheck,
  faChevronUp as farChevronUp,
  faChevronDown as farChevronDown,
  faCircle as farCircle,
  faCircleQuestion as farCircleQuestion,
  faClose as farClose,
  faCog as farCog,
  faDoorClosed as farDoorClosed,
  faDoorOpen as farDoorOpen,
  faDownLong as farDownLong,
  faFaceLaugh as farFaceLaugh,
  faFileImage as farFileImage,
  faGripVertical as farGripVertical,
  faHashtag as farHashtag,
  faHeart as farHeart,
  faHeartPulse as farHeartPulse,
  faImage as farImage,
  faImages as farImages,
  faInfo as farInfo,
  faLifeRing as farLifeRing,
  faListCheck as farListCheck,
  faListOl as farListOl,
  faMicrophoneLines as farMicrophoneLines,
  faMoon as farMoon,
  faPaintRoller as farPaintRoller,
  faPenToSquare as farPenToSquare,
  faPersonCircleQuestion as farPersonCircleQuestion,
  faPhotoFilm as farPhotoFilm,
  faPlugCircleBolt as farPlugCircleBolt,
  faPlugCirclePlus as farPlugCirclePlus,
  faPlus as farPlus,
  faShield as farShield,
  faSquare as farSquare,
  faSun as farSun,
  faTachographDigital as farTachographDigital,
  faToolbox as farToolbox,
  faTriangleExclamation as farTriangleExclamation,
  faTurnDown as farTurnDown,
  faTurnUp as farTurnUp,
  faUpLong as farUpLong,
  faUser as farUser,
  faUserCheck as farUserCheck,
  faUserClock as farUserClock,
  faUserGroup as farUserGroup,
  faUserMinus as farUserMinus,
  faUserPlus as farUserPlus,
  faUserShield as farUserShield,
  faWrench as farWrench,
} from "@fortawesome/pro-regular-svg-icons";

library.add(
  fasArrowsRotate,
  fasAt,
  fasBook,
  fasBoxesPacking,
  fasChartLine,
  fasCheck,
  fasClose,
  fasChevronUp,
  fasChevronDown,
  fasCircle,
  fasCircleQuestion,
  fasCog,
  fasDoorClosed,
  fasDoorOpen,
  fasDownLong,
  fasFaceLaugh,
  fasFileImage,
  fasGripVertical,
  fasHashtag,
  fasHeart,
  fasHeartPulse,
  fasImage,
  fasImages,
  fasInfo,
  fasLifeRing,
  fasListCheck,
  fasListOl,
  fasMicrophoneLines,
  fasMoon,
  fasPaintRoller,
  fasPenToSquare,
  fasPersonCircleQuestion,
  fasPhotoFilm,
  fasPlugCircleBolt,
  fasPlugCirclePlus,
  fasPlus,
  fasShield,
  fasSquare,
  fasSun,
  fasTachographDigital,
  fasToolbox,
  fasTriangleExclamation,
  fasTurnDown,
  fasTurnUp,
  fasUpLong,
  fasUser,
  fasUserCheck,
  fasUserClock,
  fasUserGroup,
  fasUserMinus,
  fasUserPlus,
  fasUserShield,
  fasWrench,

  farArrowsRotate,
  farAt,
  farBook,
  farBoxesPacking,
  farChartLine,
  farCheck,
  farChevronUp,
  farChevronDown,
  farCircle,
  farCircleQuestion,
  farClose,
  farCog,
  farDoorClosed,
  farDoorOpen,
  farDownLong,
  farFaceLaugh,
  farFileImage,
  farGripVertical,
  farHashtag,
  farHeart,
  farHeartPulse,
  farImage,
  farImages,
  farInfo,
  farLifeRing,
  farListCheck,
  farListOl,
  farMicrophoneLines,
  farMoon,
  farPaintRoller,
  farPenToSquare,
  farPersonCircleQuestion,
  farPhotoFilm,
  farPlugCircleBolt,
  farPlugCirclePlus,
  farPlus,
  farShield,
  farSquare,
  farSun,
  farTachographDigital,
  farToolbox,
  farTriangleExclamation,
  farTurnDown,
  farTurnUp,
  farUpLong,
  farUser,
  farUserCheck,
  farUserClock,
  farUserGroup,
  farUserMinus,
  farUserPlus,
  farUserShield,
  farWrench,
);

createApp(App)
  .component("font-awesome-icon", FontAwesomeIcon)
  .use(VueLazyload)
  .use(store)
  .use(router)
  .mount("#app");
